version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    image: assistant-backend:latest
    build: ./backend
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    depends_on:
      - postgres

  frontend:
    image: assistant-frontend:latest
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      NODE_OPTIONS: --openssl-legacy-provider
    depends_on:
      - backend

volumes:
  postgres_data:
